NVidia DGX Spark compatibilty changes

diff --git a/docker/Dockerfile.openblas b/docker/Dockerfile.openblas
--- a/docker/Dockerfile.openblas
+++ b/docker/Dockerfile.openblas
@@ -10,11 +10,12 @@ ARG CONDA_SUFFIX
 ARG CMAKE_VERSION
 ARG PYTHON_VERSION
 ARG DEVELOPER_BUILD
+ARG BUILD_SHARED_LIBS
 RUN if [ -z "${CONDA_SUFFIX}"    ]; then echo "Error: ARG CONDA_SUFFIX    not specified."; exit 1; fi \
  && if [ -z "${CMAKE_VERSION}"   ]; then echo "Error: ARG CMAKE_VERSION   not specified."; exit 1; fi \
  && if [ -z "${PYTHON_VERSION}"  ]; then echo "Error: ARG PYTHON_VERSION  not specified."; exit 1; fi \
- && if [ -z "${DEVELOPER_BUILD}" ]; then echo "Error: ARG DEVELOPER_BUILD not specified."; exit 1; fi
-
+ && if [ -z "${DEVELOPER_BUILD}" ]; then echo "Error: ARG DEVELOPER_BUILD not specified."; exit 1; fi \
+ && if [ -z "${BUILD_SHARED_LIBS}" ]; then echo "Error: ARG BUILD_SHARED_LIBS not specified."; exit 1; fi
 # Prevent interactive inputs when installing packages
 ENV DEBIAN_FRONTEND=noninteractive
 ENV TZ=America/Los_Angeles
@@ -38,10 +39,15 @@ RUN apt-get update && apt-get install -y \
 
 # Miniconda
 ENV PATH="/root/miniconda3/bin:${PATH}"
+# Accept Anaconda TOS. See https://www.anaconda.com/legal/terms/terms-of-service
+ENV CONDA_PLUGINS_AUTO_ACCEPT_TOS=true
 RUN wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-${CONDA_SUFFIX}.sh \
  && bash Miniconda3-latest-Linux-${CONDA_SUFFIX}.sh -b \
  && rm Miniconda3-latest-Linux-${CONDA_SUFFIX}.sh \
- && conda --version
+ && conda --version 
+ 
+
+
 ENV PATH="/root/miniconda3/envs/open3d/bin:${PATH}"
 RUN conda create -y -n open3d python=${PYTHON_VERSION} \
  && source activate open3d
@@ -88,6 +94,7 @@ RUN mkdir build \
     -DCMAKE_BUILD_TYPE=Release \
     -DCMAKE_INSTALL_PREFIX=~/open3d_install \
     -DDEVELOPER_BUILD=${DEVELOPER_BUILD} \
+    -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} \
     .. \
  && make -j$(nproc) \
  && make install-pip-package -j$(nproc) \
